
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Aug 31 22:56:55 UYT 2016
//----------------------------------------------------

package examples.while_ut1.parser;

/** CUP generated interface containing symbol constants. */
public interface Tokens {
  /* terminals */
  public static final int ELSE = 25;
  public static final int SEMICOLON = 12;
  public static final int ASTERISK = 7;
  public static final int DEFINED = 23;
  public static final int EQUALS_SIGN = 15;
  public static final int THEN = 9;
  public static final int WHILE = 24;
  public static final int DIVISION = 29;
  public static final int DOUBLE_EQUALS_SIGN = 27;
  public static final int TRUE = 14;
  public static final int IF = 26;
  public static final int HYPHEN_MINUS = 11;
  public static final int PLUS_SIGN = 10;
  public static final int ID = 3;
  public static final int NUM = 2;
  public static final int DO = 19;
  public static final int STRING = 28;
  public static final int LEFT_PARENTHESIS = 5;
  public static final int RIGHT_PARENTHESIS = 6;
  public static final int EOF = 0;
  public static final int DOUBLE_AMPERSAND = 17;
  public static final int LENGTH = 22;
  public static final int FALSE = 8;
  public static final int PRINT = 21;
  public static final int error = 1;
  public static final int EXCLAMATION_MARK = 4;
  public static final int LESS_THAN_OR_EQUAL = 18;
  public static final int RIGHT_CURLY_BRACKET = 16;
  public static final int LEFT_CURLY_BRACKET = 13;
  public static final int SKIP = 20;
}

