
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 27 14:55:57 UYT 2017
//----------------------------------------------------

package examples.while_ut1.parser;

/** CUP generated interface containing symbol constants. */
public interface Tokens {
  /* terminals */
  public static final int AND = 4;
  public static final int TRUE = 14;
  public static final int BICOND = 7;
  public static final int EOF = 0;
  public static final int FALSE = 15;
  public static final int COND = 6;
  public static final int ID = 10;
  public static final int COMMA = 13;
  public static final int error = 1;
  public static final int SEMICOLON = 12;
  public static final int RPAREN = 9;
  public static final int EQUALS_SIGN = 11;
  public static final int NEG = 3;
  public static final int LPAREN = 8;
  public static final int OR = 5;
  public static final int PRED = 2;
}

